app:
  version: "0.1-dev"
  debug: true
  env: "dev"
secrets:
  db:
    name: "casty"
    host: "localhost"
    port: 27017
    user: "service"
    pass: "super-secure-password"
  redis:
    masterName: "mymaster"
    sentinels:
    - "localhost:6379"
    pass: "super-secure-password"
  oauth:
    google: "./config/oauth/google_client_secret.json"
    spotify: "./config/oauth/spotify_client_secret.json"
    discord: "./config/oauth/discord_client_secret.json"
  jwt:
    expire_time: 60
    refresh_token_valid_time: 7
    private_key_path: "./config/jwt.key"
    public_key_path: "./config/jwt.pub"
  sentry_dsn: ""
  hcaptcha_secret: ""
storage_path: "/volumes/storage"