version: '3'

services:

  grpc:
    build: .
    container_name: movienight.grpc
    ports:
      - 55283:55283
    depends_on:
      - db
    restart: always
    networks:
      - backend

  db:
    image: mongo:latest
    container_name: movienight.db
    environment:
      - MONGO_INITDB_DATABASE=movienight
      - MONGO_INITDB_ROOT_USERNAME=service
      - MONGO_INITDB_ROOT_PASSWORD=ReY8H9F2SAycpj2ygYhWSjksRgcJEq
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
