name: Publish Docker image
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  push_to_registries:
    name: Push Docker image to Dockerhub and Github
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: castylab/grpc:latest
          push: true

      - name: Build alpine and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-alpine
          tags: castylab/grpc:alpine
          push: true
